[package]
name = "arm"
version = "0.1.0"
edition = "2024"

[lib]
name = "arm"
crate-type = ["cdylib"]


[package.metadata.docs.rs]
targets = ["aarch64-linux-android"] # you can add more archs!


[dependencies]
android_logger = "0.15.0"
ctor = "0.4.2"
libc = "0.2.172"
log = "0.4.27"
